@startuml
[Web App]
[Android App]
package "Server" {
    HTTP1 -- [Web Server]
    HTTP2 -- [Web Server]
    API -- [Application Server]
}
database "Database" {
    interface SQL
}
[Android App] --( HTTP2
[Web App] --( HTTP1
[Web Server] --( API
[Application Server] --( SQL
@enduml